version: "3"

services:
  app:
    image: thanita/app:1.0.0
    container_name: my-app
    ports:
      - 1337:1337
    environment:
      - DATABASE_CLIENT=
      - DATABASE_HOST=
      - DATABASE_PORT=
      - DATABASE_NAME=
      - DATABASE_USERNAME=
      - DATABASE_PASSWORD=
      - DATABASE_SSL=false
    db:
      image:
      container_name:
      ports:
  
      environment:
        - DATABASE_USERNAME=
        - DATABASE_PASSWORD=
        - DATABASE_DB=